# Generated by Django 4.0.3 on 2022-05-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_hire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
